import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KeiTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="bg-blue-50">
        <header>Header</header>
        <div className="m-1 mt-5 rounded-lg">
          <div className="grid lg:grid-cols-3 gap-4 pb-5">{children}</div>
        </div>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
