import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KeiTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>Header</header>
        <div className="bg-gray-100 m-1 mt-5 rounded-lg">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 pb-5">
            {children}
          </div>
        </div>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
